# Generated by Django 5.2.6 on 2025-11-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id_departamento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre_area", models.CharField(max_length=100)),
                ("seccion", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "DEPARTAMENTOS",
            },
        ),
        migrations.CreateModel(
            name="Nomina",
            fields=[
                ("id_nomina", models.AutoField(primary_key=True, serialize=False)),
                ("apellido", models.CharField(max_length=120)),
                ("nombre", models.CharField(max_length=120)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("departamento", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "db_table": "NOMINAS",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_rol", models.CharField(max_length=50, unique=True)),
                ("permisos", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ROLES",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "HISTORIAL_ACTIVIDAD",
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="imports/")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "pendiente"),
                            ("procesando", "procesando"),
                            ("listo", "listo"),
                            ("error", "error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                ("ok", models.IntegerField(default=0)),
                ("errores", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "IMPORT_JOBS",
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ok", "ok"), ("error", "error")],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("error_msg", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="accounts.importjob",
                    ),
                ),
            ],
            options={
                "db_table": "IMPORT_ROWS",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=120)),
                ("apellido", models.CharField(max_length=120)),
                ("documento", models.CharField(blank=True, max_length=50)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "id_departamento",
                    models.ForeignKey(
                        db_column="id_departamento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.departamento",
                    ),
                ),
                (
                    "id_nomina",
                    models.ForeignKey(
                        db_column="id_nomina",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.nomina",
                    ),
                ),
                (
                    "id_rol",
                    models.ForeignKey(
                        db_column="id_rol",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.rol",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biz",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "USUARIOS",
            },
        ),
    ]
