# Generated by Django 5.2.6 on 2025-09-11 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_created_at_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Texto libre'), ('bool', 'Verdadero/Falso'), ('scale', 'Escala 1-5'), ('choice', 'Opción múltiple'), ('multi', 'Selección múltiple'), ('date', 'Fecha'), ('time', 'Hora'), ('datetime', 'Fecha y hora'), ('email', 'Correo electrónico'), ('number', 'Número'), ('url', 'URL'), ('file', 'Archivo'), ('rating', 'Valoración'), ('matrix', 'Matriz'), ('dropdown', 'Desplegable'), ('rank', 'Clasificación'), ('longtext', 'Texto largo'), ('phone', 'Número de teléfono'), ('address', 'Dirección'), ('signature', 'Firma'), ('color', 'Selector de color'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('captcha', 'Captcha'), ('payment', 'Pago'), ('custom', 'Personalizado'), ('other', 'Otro')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
