# Generated by Django 5.2.6 on 2025-09-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_survey_owner_alter_question_question_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choices",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="required",
            field=models.BooleanField(default=True),
        ),
    ]
