# Generated by Django 5.2.6 on 2025-12-02 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_notification"),
        ("surveys", "0004_question_choices_question_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_assignments_by_departamento",
                        to="accounts.departamento",
                    ),
                ),
                (
                    "assigned_rol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_assignments_by_rol",
                        to="accounts.rol",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_assignments_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "SURVEY_ASSIGNMENTS",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("survey", "assigned_user"),
                        name="unique_user_assignment",
                    ),
                    models.UniqueConstraint(
                        fields=("survey", "assigned_rol"), name="unique_rol_assignment"
                    ),
                    models.UniqueConstraint(
                        fields=("survey", "assigned_departamento"),
                        name="unique_depto_assignment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("assigned_user__isnull", False),
                            ("assigned_rol__isnull", False),
                            ("assigned_departamento__isnull", False),
                            _connector="OR",
                        ),
                        name="at_least_one_assignment_target",
                    ),
                ],
            },
        ),
    ]
